### ISSUE TITLE
OMOP環境構築手順書の5.1項についての質問

### ISSUE THREAD

**Issue by somacells** [RWD-data-environment-in-Hospital/OMOP.OHDSI.implementation#24]
@aki-michihiko さん、
https://github.com/RWD-data-environment-in-Hospital/OMOP.OHDSI.implementation/blob/main/OMOP.OHDSI_Verification_Environment_Construction_Procedure_Manual.md
の
５．３．Achilles / CohortMethod のインストール
の項ですが、ATLASではないでしょうか？

**Comment by aki-michihiko** [comment]
Achilles / CohortMethod は、ATLASは下記の通り別物との認識です。
ご確認をお願いします。
  https://www.ohdsi.org/demos/

**Comment by somacells** [comment]
すみません、ATLAS / CohortMethod ではなく、Achilles / CohortMethodでよいですよね。。

**Comment by aki-michihiko** [comment]
はい、Achilles / CohortMethodです。よろしくお願いします。

**Comment by somacells** [comment]
了解です。ありがとうございます。お手数をおかけしました。
